import { BridgeTxn } from '../bridge';
// import { ENV } from '../utils/dotenv'; // not sure if we can initialize DB without ENV
import { db } from './db';
import { exampleBridgeTxn } from '../test/test-helper/test-example';
import { EXAMPLE_TXN_FOR_CREATE_TEST } from '../src/test/test-helper/test-examples';
import { BridgeTxnStatusEnum } from '../common/src/type/txn';

const EXAMPLE_TXN_FOR_CREATE_TEST = {
  createdTime: 1656171676417n,
  fixedFeeAtom: 10000000000n,
  fromAddr: 'ACCSSTKTJDSVP4JPTJWNCGWSDAPHR66ES2AZUAH7MUULEY43DHQSDNR7DA',
  fromAmountAtom: 12345678901n,
  fromTokenId: TokenId.goNEAR,
  fromTxnId: '2HXYPGDY2EDVERXXQH6UKAT22EQGXWGWPWSJFY3G22AQLNZYTTDA',
  marginFeeAtom: 24691358n,
  toAddr: 'abstrlabs-test.testnet',
  toAmountAtom: 2320987543n,
  toTokenId: TokenId.NEAR,
  toTxnId: '2VE7QxZZ92PKGkzJzbhf44MTeoxU4LBGXSgXVVAYHNee',
}

describe('DATABASE test', () => {
  describe('CRUD test with Bridge Txn', () => {
    it('create a transaction', async () => {
      // should test with bridgeTxn
      EXAMPLE_TXN_FOR_CREATE_TEST.txnComment = 'generated by db.spec.ts';
      const res = await db.createTxn(EXAMPLE_TXN_FOR_CREATE_TEST);
      EXAMPLE_TXN_FOR_CREATE_TEST.txnComment = null;
      expect(typeof res).toBe('number');
    });
    it.skip('read a transaction', async () => {
      // skip: serialize bigint
      // should test with bridgeTxn
      exampleBridgeTxn.dbId = exampleBridgeTxn.getDbId();
      const res = await db.readTxn(exampleBridgeTxn.dbId);
      expect(typeof res).toBe('object');

      expect(BridgeTxn.fromDbItem(res)).toEqual(exampleBridgeTxn);
    });
    it.skip('update a transaction', async () => {
      exampleBridgeTxn.txnStatus = BridgeTxnStatusEnum.DONE_OUTGOING;
      exampleBridgeTxn.toTxnId = 'some_fake_txn_id';
      const res1 = await db.updateTxn(exampleBridgeTxn);
      expect(typeof res1).toBe('number');

      // read the updated transaction
      // should test with bridgeTxn
      exampleBridgeTxn.dbId = exampleBridgeTxn.getDbId();
      const res2 = await db.readTxn(exampleBridgeTxn.dbId);
      expect(typeof res2).toBe('object');
      // verify updated transaction is correct
      expect(BridgeTxn.fromDbItem(res2)).toEqual(exampleBridgeTxn);
    });
  });
  it('should read all txn in table', async () => {
    const res = await db.readAllTxn();
    expect(typeof res).toBe('object');
    expect(Array.isArray(res)).toBe(true);
    // expect(res.length).toBeGreaterThan(0);
  });
});
