-- DDL generated by Postico 1.5.20
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE user_mint_request (
    id SERIAL PRIMARY KEY,
    near_address character varying(64) NOT NULL,
    algorand_address character varying(58) NOT NULL,
    amount bigint NOT NULL,
    create_time bigint NOT NULL,
    request_status text NOT NULL,
    near_tx_hash character varying(63) NOT NULL,
    algo_txn_id character varying(63)
);
COMMENT ON COLUMN user_mint_request.near_address IS 'max==64. from https://docs.near.org/docs/concepts/account#implicit-accountsMore than 64 characters (including .testnet) from https://wallet.testnet.near.org/create';
COMMENT ON COLUMN user_mint_request.algorand_address IS 'all algorand ==58 https://developer.algorand.org/docs/get-details/accounts/#keys-and-addresses';
COMMENT ON COLUMN user_mint_request.amount IS 'of unit 10^-10 goNEAR.';
COMMENT ON COLUMN user_mint_request.create_time IS 'int, in milisecond';
COMMENT ON COLUMN user_mint_request.request_status IS 'should use txn_status ENUM';
COMMENT ON COLUMN user_mint_request.near_tx_hash IS 'checked always 44, but not sure. (seems  32 bytes in base58) using 63.';
COMMENT ON COLUMN user_mint_request.algo_txn_id IS 'checked always 52, but not sure. using 63. 32 bytes https://developer.algorand.org/docs/get-details/dapps/avm/teal/specification/#loading-values not in base 58, full caps. so its longer.';

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_mint_request_pkey ON user_mint_request(id int4_ops);
