-- source of truth: src/index.ts: enum BridgeTxnStatus
CREATE TYPE txn_status_enum AS ENUM (
  'DOING_INITIALIZE',
  'DONE_INITIALIZE',
  'ERR_SEVER_INTERNAL',
  'ERR_AWS_RDS_DB',
  'DOING_INCOMING',
  'ERR_TIMEOUT_INCOMING',
  'ERR_VERIFY_INCOMING',
  'DONE_INCOMING',
  'ERR_MAKE_OUTGOING',
  'DOING_OUTGOING',
  'DOING_VERIFY',
  'ERR_TIMEOUT_OUTGOING',
  'DONE_OUTGOING',
  'USER_CONFIRMED'
  );
