#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# unit tests and integration tests
yarn unit-test --bail
# first, check server is running
yarn start & yarn jest ./src/test/integration-test/api.test.ts --testNamePattern='hosted API root server returns welcome JSON on GET'
pkill -f -n yarn start