#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# first, check server is running
yarn jest --runTestsByPath='./src/test/integration-test/api.test.ts' --testNamePattern='hosted API server returns welcome JSON on GET'
# unit tests and integration tests
yarn test --bail